"""Demo policy rules for seeding realistic compliance checks."""

DEMO_POLICY_RULES = [
    {
        "name": "Mask Social Security Numbers",
        "description": "SSNs must be masked unless stored in approved PII fields.",
        "severity": "high",
        "category": "PII",
        "pattern_type": "regex",
        "pattern": "\\b\\d{3}-\\d{2}-\\d{4}\\b",
        "scope": ["body", "attachments"],
        "remediation": "Replace SSNs with masked format (***-**-1234).",
    },
    {
        "name": "No credit card numbers in notes",
        "description": "Payment card data must not appear in free-form notes.",
        "severity": "critical",
        "category": "PCI",
        "pattern_type": "regex",
        "pattern": "\\b(?:\\d[ -]*?){13,16}\\b",
        "scope": ["notes"],
        "remediation": "Remove card numbers and store tokenized reference instead.",
    },
    {
        "name": "HIPAA terms require consent",
        "description": "Clinical data references must include consent statement.",
        "severity": "medium",
        "category": "Healthcare",
        "pattern_type": "keyword",
        "pattern": "HIPAA",
        "scope": ["body"],
        "remediation": "Append consent clause or redact clinical references.",
    },
    {
        "name": "Export-controlled terms",
        "description": "Export-controlled terms require legal review.",
        "severity": "high",
        "category": "Export",
        "pattern_type": "keyword",
        "pattern": "export-controlled",
        "scope": ["body", "attachments"],
        "remediation": "Escalate to legal and mark as export-controlled.",
    },
    {
        "name": "Confidential pricing language",
        "description": "Pricing clauses must include confidentiality tag.",
        "severity": "low",
        "category": "Commercial",
        "pattern_type": "semantic",
        "pattern": "pricing confidentiality clause",
        "scope": ["sections"],
        "remediation": "Add confidentiality designation to pricing section.",
    },
]
